spring:
  profiles:    active: dev
  cloud:    config:      server:        git:          uri: https://github.com/spring-boot-cloud-microservices/config-repo
          skip-ssl-validation: true
eureka:  client:    register-with-eureka: true
